<?php
    $sql_dmd    = "SELECT "
                    .   "CLDEMAND.CLDEMAND_IMAGE_FILE_NAME, "
                    .   "CLDEMAND.CLDEMAND_POL_NUM, "
                    .   "CLDEMAND.CLDEMAND_LOSS_SEQ, "
                    .   "CLDEMAND.CLDEMAND_CLMT_SEQ, "
                    .   "CLDEMAND.CLDEMAND_COV_LINE, "
                    .   "CASE IMAGE.IMAGE_BATCH_PRT "
                    .       "WHEN 'N' THEN 'O' "
                    .       "ELSE 'C' "
                    .   "END AS STATUS, "
                    .   "CLDEMAND.CLDEMAND_ATTORNEY_EXTRK_TYPE, "
                    .   "CLDEMAND.CLDEMAND_ATTORNEY_EXTRK_NUM, "
                    .   "CLDEMAND.CLDEMAND_PROVIDER_EXTRK_TYPE, "
                    .   "CLDEMAND.CLDEMAND_PROVIDER_EXTRK_NUM, "
                    .   "CLDEMAND.CLDEMAND_BEGIN_SERVICE_DATE, "
                    .   "CLDEMAND.CLDEMAND_END_SERVICE_DATE, "
                    .   "CLDEMAND.CLDEMAND_DUE_DATE, "
                    .   "CLDEMAND.CLDEMAND_RESPONSE_DATE, "
                    .   "CLDEMAND.CLDEMAND_REASON, "
                    .   "CLDEMAND.CLDEMAND_RESPONSE_NOT_APP, "
                    .   "CLDEMAND.CLDEMAND_DEMAND_PROPER, "
                    .   "CLDEMAND.CLDEMAND_RECV_DATE, "
                    .   "IMAGE.IMAGE_OWNER, "
                    .   "IMAGE.IMAGE_CREATE_USER, "
                    .   "IMAGE.IMAGE_CREATE_DATE, "
                    .   "IMAGE.IMAGE_CREATE_TIME, "
                    .   "IMAGE.IMAGE_LAST_USER, "
                    .   "IMAGE.IMAGE_LAST_DATE, "
                    .   "IMAGE.IMAGE_LAST_TIME, "
                    .   "IMAGE.IMAGE_FILE_NAME, "
                    .   "IMAGE.IMAGE_BATCH_PRT "
                    . "FROM "
                    .   "OSIS.CLDEMAND, OSIS.IMAGE ";
    echo $sql_dmd;